# =========================
# GENERAL OPTIONS
# =========================
dataset_cerra: "/projects/0/prjs0951/Devashish/NeurIPS-workshop/CentralEurope_2014_2020/CERRA" 
dataset_era5: "/projects/0/prjs0951/Devashish/NeurIPS-workshop/CentralEurope_2014_2020/ERA5"
model: FNO                 # Model architecture
subset_ds: 0                   # 0 = full dataset, >0 = subset size
seed: 32
n_workers: 16                    # Dataloader workers
load: /home/csaccardi1/Devashish_thesis/PSD-Downscaling_thesis/saved_models/FNO-downscaling-lossfn_Carlo-FNO-01_14_11-8812/min_val_loss.ckpt
restore_opt: 1                    # 0 = do not restore optimizer
precision: "16-mixed"              # 32 | 16 | 16-mixed | bf16
eval: test                    # val | test | null → train
wandb_project: finetune
run_name: FNO-snellius-testv2     # Optional run name
# =========================
# DATASET SETTINGS
# =========================
output_variables: null             # List of vars to predict
img_in_channels: 15        ##from 15
img_out_channels: 5
img_resolution: [368, 368]

# =========================
# MODEL SETTINGS
# =========================

num_fno_layers: 2
fno_layer_size: 64
num_fno_modes: 16
fno_padding: 8
coord_features: True
decoder_layers: 1
decoder_layer_size: 64

# =========================
# TRAINING SETTINGS
# =========================
val_interval: 1
lr: 2.0e-4
epochs: 200
batch_size: 8
lr_decay: 1
lr_rampup: 0
grad_clip_threshold: null          # Set a number to enable clipping
checkpoint_level: 0
init_lambda: 0.0
max_lambda: 0.0001
loss_type: 'Fourier_Carlo'
resume: null
savepreds_path: null
