# =========================
# GENERAL OPTIONS
# =========================
dataset_cerra: "/projects/0/prjs0951/Devashish/NeurIPS-workshop/CentralEurope_2014_2020/CERRA" 
dataset_era5: "/projects/0/prjs0951/Devashish/NeurIPS-workshop/CentralEurope_2014_2020/ERA5"
model: UNet-CNN                 # Model architecture
subset_ds: 0                      # 0 = full dataset, >0 = subset size
seed: 32
n_workers: 16                   # Dataloader workers
load: null
restore_opt: 0                     # 0 = do not restore optimizer
precision: "16-mixed"              # 32 | 16 | 16-mixed | bf16
eval: null                       # val | test | null → train
wandb_project: finetune
run_name: UNet-trainv2-PSDLoss      # Optional run name
# =========================
# DATASET SETTINGS
# ===========================
output_variables: null             # List of vars to predict
img_in_channels: 15
img_out_channels: 5
img_resolution: [368, 368]

# =========================
# MODEL SETTINGS
# =========================
N_grid_channels: 4
embedding_type: zero
model_channels: 64
channel_mult: [1, 2, 2]
attn_resolutions: [16]
model_type: SongUNetPosEmbd

# =========================
# TRAINING SETTINGS
# =========================
val_interval: 1
lr: 2.0e-4
epochs: 200
batch_size: 16
lr_decay: 1
lr_rampup: 0
grad_clip_threshold: null          # Set a number to enable clipping
checkpoint_level: 0
init_lambda: 0.0
max_lambda: 0.0001
loss_type: 'Fourier_Carlo'
resume: null
savepreds_path: null

